# Generated by Django 2.0.2 on 2018-02-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('OrderID', models.IntegerField()),
                ('VendorName', models.CharField(max_length=500)),
                ('Details', models.CharField(max_length=1000)),
            ],
        ),
    ]
